version: "3"

services:
  bw-matcher:
    container_name: bw-matcher
    image: bw-matcher
    build: ./
    ports:
      - "8002:8002"
    expose:
      - "8002"
    networks:
      esnet:
    environment:
      - "SPRING_PROFILES_ACTIVE=standalone"

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge
