server:
  port: 8002
  servlet:
    context-path: /
spring:
  application:
    name: BWMatcher
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  # static properties
  app:
    name: ${spring.application.name}
    description: --

logging:
  level:
    root: info
