server:
  port: 8002
  servlet:
    context-path: /
spring:
  application:
    name: BWMatcher
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: broker:9092
    consumer:
      group-id: matcher
    template:
      default-topic: draws
  health:
    elasticsearch:
      enabled: false

eureka:
  instance:
    lease-expiration-duration-in-seconds: 240
    lease-renewal-interval-in-seconds: 120
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  # static properties
  app:
    name: ${spring.application.name}
    description: --

logging:
  level:
    root: info
